"""add final_asnwer

Revision ID: 613c0393bffd
Revises: 
Create Date: 2023-08-02 17:56:55.288170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '613c0393bffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('phone', sa.String(length=13), nullable=True),
    sa.Column('full_name', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('city', sa.String(length=30), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=True),
    sa.Column('trading_knowledge', sa.Boolean(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('english_level', sa.String(length=100), nullable=True),
    sa.Column('what_attracted', sa.String(length=100), nullable=True),
    sa.Column('agreement', sa.Boolean(), nullable=True),
    sa.Column('resume_data', sa.LargeBinary(), nullable=True),
    sa.Column('resume_filename', sa.String(length=100), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('family_status', sa.String(length=50), nullable=True),
    sa.Column('company_knowledge', sa.Boolean(), nullable=True),
    sa.Column('company_knowledge_text', sa.Text(), nullable=True),
    sa.Column('final_answer', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('company')
    op.drop_table('candidate')
    # ### end Alembic commands ###
