"""resume filepath

Revision ID: 8301a3beead5
Revises: 873f647f047b
Create Date: 2023-08-02 19:20:46.179553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8301a3beead5'
down_revision = '873f647f047b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('resume_filepath', sa.String(length=100), nullable=True))
    op.drop_column('candidate', 'resume_filename')
    op.drop_column('candidate', 'resume_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('resume_data', sa.BLOB(), nullable=True))
    op.add_column('candidate', sa.Column('resume_filename', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('candidate', 'resume_filepath')
    # ### end Alembic commands ###
