"""add rejection reason

Revision ID: 873f647f047b
Revises: 613c0393bffd
Create Date: 2023-08-02 18:02:24.523653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873f647f047b'
down_revision = '613c0393bffd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'rejection_reason')
    # ### end Alembic commands ###
