"""initial

Revision ID: 958506d6347a
Revises: 
Create Date: 2023-08-02 12:41:35.366791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958506d6347a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
