"""add language

Revision ID: 97b817f35739
Revises: d086c44a623c
Create Date: 2024-02-29 12:34:55.297640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b817f35739'
down_revision = 'd086c44a623c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('processed', sa.Boolean(), nullable=True))
    op.add_column('candidate', sa.Column('language', sa.String(length=2), nullable=True))
    op.add_column('candidate', sa.Column('last_activity', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidate', 'last_activity')
    op.drop_column('candidate', 'language')
    op.drop_column('application', 'processed')
    # ### end Alembic commands ###
